import{a as h,S as w,i as n}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const u=document.querySelector(".loader");function m(){u.style.display="block"}function f(){u.style.display="none"}async function g(r,s){const l="44758497-ea11318ae0823ef09cb8fbdb5",t=new URLSearchParams({key:l,q:r,image_type:"photo",per_page:20,page:s}),{data:o}=await h.get(`https://pixabay.com/api/?${t}`);return console.log(o),o}function d(){gallery.innerHTML=""}const b=document.querySelector("#gallery");function y(r){const s=r.map(e=>`
     <div class="image-card">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" width=360 height=200 alt="${e.tags}" /></a>
            <div class="image-text">
            <ul>
        <li><p>likes:</p><p>${e.likes}</p></li>
        <li><p>views:</p><p>${e.views}</p></li>
        <li><p>comments:</p><p>${e.comments}</p></li>
        <li><p>downloads:</p><p>${e.downloads}</p></li>
        </ul>
        </div>
      </div>
    `).join("");b.insertAdjacentHTML("beforeend",s),L.refresh()}const L=new w(".image-card a",{captionsData:"alt",captionDelay:250,navText:["&larr;","&rarr;"],closeText:"&times;"}),p=document.querySelector(".btn"),P=document.querySelector("#search-form");let i=1,a="";P.addEventListener("submit",async r=>{if(r.preventDefault(),d(),i=1,a=new FormData(r.target).get("query"),!a.trim())return n.show({position:"topRight",backgroundColor:"orange",message:"Будь ласка, введіть пошуковий запит."});if(a&&a.trim())try{m();const e=await g(a.trim(),i);console.log(e.hits),e.totalHits>0&&n.show({position:"topRight",backgroundColor:"green",message:`Found ${e.totalHits} results.`}),e.totalHits===0&&(d(),console.log(e.totalHits),n.show({position:"topRight",backgroundColor:"yellow",message:`Found ${e.totalHits} results.`})),y(e.hits),i+=1,i>1&&(p.textContent="Fetch more posts",p.style.display="block")}catch(e){console.log(e),n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{f()}});p.addEventListener("click",async()=>{if(a&&a.trim())try{m();const r=await g(a.trim(),i);y(r.hits),i+=1}catch(r){console.log(r),n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{f()}});
//# sourceMappingURL=commonHelpers.js.map
