import{a as y,S as h,i as l}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const p=document.querySelector(".loader");function f(){p.style.display="block"}function u(){p.style.display="none"}async function m(t){let s=1;const r=20,n="44758497-ea11318ae0823ef09cb8fbdb5",e=new URLSearchParams({key:n,q:t,image_type:"photo",_per_page:r,_page:s});return(await y.get(`https://pixabay.com/api/?${e}`)).data.hits}function g(t){const s=document.querySelector("#gallery");if(!s){console.error("Елемент #gallery не знайдений в DOM.");return}if(t.length===0){s.innerHTML="<p>Нічого не знайдено.</p>";return}const r=t.map(e=>`
      <div class="image-card">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" /></a>
            <div class="image-text">
        <p>likes: ${e.likes}</p>
        <p>views: ${e.views}</p>
        <p>comments: ${e.comments}</p>
        <p>downloads: ${e.downloads}</p>
        </div>
      </div>
    `).join("");s.insertAdjacentHTML("beforeend",r),new h(".image-card a",{captionsData:"alt",captionDelay:250,navText:["&larr;","&rarr;"],closeText:"&times;"}).refresh()}const d=document.querySelector(".btn"),w=document.querySelector("#search-form");let i=1,a="";w.addEventListener("submit",async t=>{if(t.preventDefault(),a=new FormData(t.target).get("query"),a&&a.trim())try{f();const r=await m(a.trim(),i);console.log(r.data),r.totalHits>0&&l.show({position:"topRight",backgroundColor:"green",message:`Found ${r.totalHits} results.`}),g(r),i+=1,i>1&&(d.textContent="Fetch more posts",d.style.display="block")}catch(r){console.log(r),l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{u()}});d.addEventListener("click",async()=>{if(a&&a.trim())try{f();const t=await m(a.trim(),i);g(t),i+=1}catch(t){console.log(t),l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{u()}});
//# sourceMappingURL=commonHelpers.js.map
