import{a as y,S as h,i as l}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p=document.querySelector(".loader");function f(){p.style.display="block"}function u(){p.style.display="none"}async function m(r,s){const i="44758497-ea11318ae0823ef09cb8fbdb5",e=new URLSearchParams({key:i,q:r,image_type:"photo",per_page:20,page:s}),t=await y.get(`https://pixabay.com/api/?${e}`);return console.log("результат ${response.data}"),t.data.hits}function g(r){const s=document.querySelector("#gallery");if(!s){console.error("Елемент #gallery не знайдений в DOM.");return}if(r.length===0){s.innerHTML="<p>Нічого не знайдено.</p>";return}const o=r.map(e=>`
      <div class="image-card">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" /></a>
            <div class="image-text">
        <p>likes: ${e.likes}</p>
        <p>views: ${e.views}</p>
        <p>comments: ${e.comments}</p>
        <p>downloads: ${e.downloads}</p>
        </div>
      </div>
    `).join("");s.insertAdjacentHTML("beforeend",o),new h(".image-card a",{captionsData:"alt",captionDelay:250,navText:["&larr;","&rarr;"],closeText:"&times;"}).refresh()}const d=document.querySelector(".btn"),w=document.querySelector("#search-form");let n=1,a="";w.addEventListener("submit",async r=>{if(r.preventDefault(),n=1,a=new FormData(r.target).get("query"),a&&a.trim())try{f();const o=await m(a.trim(),n);console.log(o),o.totalHits>0&&l.show({position:"topRight",backgroundColor:"green",message:`Found ${o.totalHits} results.`}),g(o),n+=1,n>1&&(d.textContent="Fetch more posts",d.style.display="block")}catch(o){console.log(o),l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{u()}});d.addEventListener("click",async()=>{if(a&&a.trim())try{f();const r=await m(a.trim(),n);g(r),n+=1}catch(r){console.log(r),l.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{u()}});
//# sourceMappingURL=commonHelpers.js.map
